### ISSUE TITLE
During conf: attendance lists

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#1]
Generate a list of names registered to go to each social event, either with partner/children's names, or delegates name plus 1 adult, 2 children.

An example of useful reports is attached.

Launchpad Details: [#LP356037](https://bugs.launchpad.net/bugs/356037) François Marier - 2009-04-06 15:44:32 +1000

**Comment by KathyReid** [comment]
Categorised as reporting feature request. 
Thanks for raising, @johnf

**Comment by johnf** [comment]
Cleaning up some old issues I own
