### ISSUE TITLE
CFP: The review summary screen should produce equal ranks for equal scores

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#11]
http://linux.conf.au/proposal/summary ranks talks by average score. Talks that have equal scores will be arbitarily ranked among themselves, eg here talks X and Y have equal scores:

41 Talk W Score: 13
42 Talk X Score: 12
43 Talk Y Score: 12
44 Talk Z Score: 11

This should be:

41 Talk W Score: 13
Equal 42 Talk X Score: 12
Equal 42 Talk Y Score: 12
44 Talk Z Score: 11

Launchpad Details: [#LP280511](https://bugs.launchpad.net/bugs/280511) Mary Gardiner - 2008-10-09 12:38:12 +1100

**Comment by lod** [comment]
I think this bug report is incorrect or obsolete but would appreciate feedback from experienced reviewers.

I have included below the table from the summary page, it contains some sample data from my dev system. The first column which is portrayed as the rank is actually the id of the proposal. Talks are sorted by score and with an equal score are ranked arbitrarily but it seems from my position of ignorance that that should be acceptable, the scores are clearly shown.

I could add a signifier to the score column, something like =2.00 but that feels like just adding noise.

Far more interesting questions to me would be why are we showing the id number at all?
And why are they sorted from worst to best?

<table>
<tbody><tr>
	<th>#</th>
	<th>Proposal</th>
	<th>Submitters</th>
	<th>Avg Score</th>
	<th>Reviewers</th>
	<th>Winning Stream</th>
</tr>

<tr class="even">
	<td>
		<a href="/proposal/2/review">2</a>
	</td>
	<td>
		<a href="/proposal/2/review">A title</a>
	</td>
	<td>
		Admin User, 
	</td>
	<td>
		-1.00
	</td>
	<td>
	Test Reviewer, 
	</td>

	<td>
		here he comes (1)
	</td>
</tr>

<tr class="odd">
	<td>
		<a href="/proposal/1/review">1</a>
	</td>
	<td>
		<a href="/proposal/1/review">Dummy talk</a>
	</td>
	<td>
		Test Submitter, 
	</td>
	<td>
		2.00
	</td>
	<td>
	Test Reviewer
	</td>

	<td>
		the saviour is tasty (1)
	</td>
</tr>
</tbody>
</table>

**Comment by johnf** [comment]
Cleaning up some old issues I own
