### ISSUE TITLE
After conf: import attendee feedback data

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#12]
Michael Davies (on lca09_papers): Hopefully zookeepr might in the future provide an attendee feedback mechanism that makes it easy to provide feedback, and can be merged with historical data, and can be viewed by the PapersCtte.

Launchpad Details: [#LP338562](https://bugs.launchpad.net/bugs/338562) sabik - 2009-03-06 15:02:24 +1100

**Comment by KathyReid** [comment]
Can we leverage off something like Joind.In?

**Comment by johnf** [comment]
Cleaning up some old issues I own
