### ISSUE TITLE
During conf: delegate signup pages for ad-hoc events

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#13]
Allow delegates to create "signup pages" for their ad-hoc events (e.g. BoFs, distillery tours, etc.).

They could then link to their signup page from the mailing list and track how many people are interested (and get in touch with them by email/phone).

Launchpad Details: [#LP356016](https://bugs.launchpad.net/bugs/356016) François Marier - 2009-04-06 14:45:54 +1000

**Comment by KathyReid** [comment]
Closing issue; use the Wiki
