### ISSUE TITLE
Volunteer: Add a field or fields to allow the organisers to assign a job to a volunteer

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#17]
Allow the organisers to assign people to specific volunteer jobs. This should be seperate to the volunteer requested areas as these won't necessarily be the same data.

Launchpad Details: [#LP359879](https://bugs.launchpad.net/bugs/359879) James Iseppi - 2009-04-12 16:25:16 +1000

**Comment by KathyReid** [comment]
Closing this; most job tracking is done through RT or systems like Trello.
