### ISSUE TITLE
Investigate using Pyramid auth for Zookeepr

### ISSUE THREAD

**Issue by duncan-zookeepr** [zookeepr/zookeepr#174]
Part of the PyCon 2012 code sprint

**Comment by KathyReid** [comment]
Thanks Duncan for raising this, appreciated. We are now using a salted hash as of Zookeepr LCA2016 hackfest, now closing issue.

**Comment by KathyReid** [comment]
https://github.com/zookeepr/zookeepr/pull/335 <- adding reference if required for tracking.

**Comment by lod** [comment]
Can we reopen this?

The central issue is to use a common authentication for both the pylons and pyramid code base.
The hash salting is actually independent.

As both pylons and pyramid support repoze it looks to be a viable way forward.
