### ISSUE TITLE
Want to be able to sort attendees by last name

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#22]
I was informed that Zookeepr currently cannot sort attendees by last name.

Launchpad Details: [#LP352085](https://bugs.launchpad.net/bugs/352085) Henry - 2009-03-31 12:46:53 +1100

**Comment by lod** [comment]
Closing because there isn't enough detail.

Not clear which list we are talking about or why sorting by last name is desired.

There are other tickets which discuss generic sorting requirements.
