### ISSUE TITLE
DB initialisation problem with ceiling->parent_id

### ISSUE THREAD

**Issue by barryrowlingson** [zookeepr/zookeepr#283]
Trying to setup zk from latest git source, following NEW_INSTALL:

Gets as far as initialising the db with alembic:

```
alembic --config development.ini upgrade head
[one big traceback ends]
 File "/nobackup/rowlings/Downloads/Conference/Env2/lib/python2.6/site-packages/SQLAlchemy-0.8.1-py2.6-linux-i686.egg/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) column "parent_id" of relation "ceiling" does not exist
LINE 1: INSERT INTO ceiling (parent_id, name, max_sold, available_fr...
                             ^
 'INSERT INTO ceiling (parent_id, name, max_sold, available_from, available_until) VALUES (%(parent_id)s, %(name)s, %(max_sold)s, %(available_from)s, %(available_until)s) RETURNING ceiling.id' {'parent_id': None, 'available_from': None, 'available_until': None, 'name': 'conference-all', 'max_sold': None}
```

Looking in the alembic file, there seems to be a migration about adding parent_id in 3b1b405d632e_.py but the error message implies otherwise. This is beyond my skillset anyway (am more a django person).

Afterwards my DB doesn't show any new tables, but I suspect this is all done in a transaction and so fails.

**Comment by KathyReid** [comment]
Had a chat with @noisymime, this issue has been resolved. Many thanks Barry for reporting - appreciated. Best, K.
