### ISSUE TITLE
NEW_INSTALL challenge: Alembic stall in some cases

### ISSUE THREAD

**Issue by elena** [zookeepr/zookeepr#284]
James seems to understand this bug.

There was a workaround that was implemented, this seems to cause other problems -- need work out a way to not need to that work around the workaround.

It is necessary to read these emails to understand what the problem:
http://lists.zookeepr.org/public/zookeepr-devel/2013-April/000505.html
http://lists.zookeepr.org/public/zookeepr-devel/2013-April/000506.html

The difficulty seems to be:
~ Fixing for new users will break for current users
~ Works already for current users.

**Comment by KathyReid** [comment]
@iseppi has done some work on alembic during Zookeepr hackfest this weekend, and this is being handled through configurations. Raising as critical, assigning to @iseppi

**Comment by lod** [comment]
I can confirm that this is solved and a trial installation for a new database worked successfully for me.

Work is mostly by @iseppi in #405 and @neillc in #406.

There is no event data populated as this isn't required for a basic install. The important populations are tables such as role which don't vary between event.
