### ISSUE TITLE
Problems with finish_signup form

### ISSUE THREAD

**Issue by fmarier** [zookeepr/zookeepr#287]
Steps to reproduce:

1. click "Register" and create a new manual account
2. click "Sign out"
3. click "Sign in"
4. create a new account by clicking on the Persona button
5. don't submit the form that's asking for more info (name, address, etc.)
6. click "Sign out"
7. click "Sign in"
8. enter the login details for the manual account and click "sign in"

At this point, you will hit a 500 Unexpected error page and the URL will be `/person/persona_login`.

In the error log, we see this:

    [Tue Sep 10 20:46:43 2013] [error] File '/srv/http/lca2014.linux.org.au/zookeepr/zkpylons/lib/helpers.py', line 540 in check_for_incomplete_profile
    [Tue Sep 10 20:46:43 2013] [error]   if not person.firstname or not person.lastname or not person.i_agree or (lca_rego['personal_info']['home_address'] == 'yes' and (not person.address1 or not person.city or not person.postcode)):
    [Tue Sep 10 20:46:43 2013] [error] AttributeError: 'str' object has no attribute 'firstname'

**Comment by KathyReid** [comment]
Closing issue, Persona support being removed as per ZooKeepr hackfest May 2015.
