### ISSUE TITLE
CFP: print proposals formatted for papers & programming f2f

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#3]
(12:05:59) Steve Walsh: feature request for 010's ZK
(12:06:55) Steve Walsh: paperselection report that does the paper info on a (cutable) strip with papername, submitter, avg score, etc
(12:07:16) Steve Walsh: so they can print it out, run it through a guillotine, bring to papers
(12:07:29) Steve Walsh: trivial to do, or OMFG what are you doing to me
(12:08:02) sabik: should be trivial...

Launchpad Details: [#LP269654](https://bugs.launchpad.net/bugs/269654) sabik - 2008-09-13 12:12:15 +1000

**Comment by lod** [comment]
Dear review people,
Is the current CSV technique sufficient?

Alternatively I can easily put together a printable file such as
https://gist.githubusercontent.com/lod/3c23277038cc68723320/raw/921b665846fb0e500480dfba48c3487edaa88dbd/proposal_strips.ps

**Comment by stevewalsh** [comment]
This has long since been overtaken by a python script that formats the talk information to suit a sheet of perforated card stock. 

This issue can effectively be closed as 'resolved'

**Comment by johnf** [comment]
Cleaning up some old issues I own
