### ISSUE TITLE
editing your review loses its previous values

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#31]
If I go to edit my review, for example to add more text, zookeepr should retain the current values for all fields.  It apparently gives me back the text (thank goodness) but resets the score and dropdowns to the defaults, which is annoying.

Launchpad Details: [#LP411227](https://bugs.launchpad.net/bugs/411227) Martin Pool - 2009-08-10 12:16:38 +1000

**Comment by KathyReid** [comment]
@jhesketh @noisymime @fmarier can anyone tell me if this is still an open bug?

**Comment by lod** [comment]
I can confirm that this is fixed, both the miniconf and stream combo boxes work.
I will shortly introduce a patch which adds this to the functional testing.

**Comment by johnf** [comment]
Cleaning up some old issues I own
