### ISSUE TITLE
Ubuntu 14.04 LTS Trusty Tahir does not support pbkdf2 hashlib

### ISSUE THREAD

**Issue by KathyReid** [zookeepr/zookeepr#336]
The hashlib in Python 2.7.8 - pbkdf2 - which is used for salting the hash for passwords, is not available in Ubuntu 14.04 LTS Trusty Tahir. This version of Ubuntu uses Python 2.75. 

The version of Python in Debian Jessie is 2.7.9

WAY FORWARD: We need to support Ubuntu as a deploy environment

**Comment by fmarier** [comment]
Options:

1. require jessie / utopic or later
2. on trusty, require [this PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa)
3. switch from pbkdf2 to sha256
4. switch from hashlib to the [pbkdf2](https://www.dlitz.net/software/python-pbkdf2/) module

While #3 is the crappiest option of the bunch, but it is also the fastest if we want to support trusty out of the box. I will work on that now. Hopefully we can then look into #4.

**Comment by KathyReid** [comment]
Nice.
