### ISSUE TITLE
devel list is bouncing

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#34]
This is the mail system at host beaker.inodes.org.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

```
              The mail system
```

zookeepr-devel@zookeepr.org: mail for zookeepr.org loops back to myself

Final-Recipient: rfc822; zookeepr-devel@zookeepr.org
Original-Recipient: rfc822;zookeepr-devel@zookeepr.org
Action: failed
Status: 5.4.6
Diagnostic-Code: X-Postfix; mail for zookeepr.org loops back to myself

Launchpad Details: [#LP635328](https://bugs.launchpad.net/bugs/635328) croy - 2010-09-11 07:51:20 +1000

**Comment by KathyReid** [comment]
sent message to see if this is still an open issue

**Comment by johnf** [comment]
Cleaning up some old issues I own
