### ISSUE TITLE
Add email verification decorator to funding and volunteer applications

### ISSUE THREAD

**Issue by KathyReid** [zookeepr/zookeepr#344]
This feature request was burned down during May 2015 ZooKeepr hackfest. 
Logging here so that we have visibility of where it was introduced into master.

**Comment by KathyReid** [comment]
@jhesketh just confirming this one is done - it was in our done column. 
I'll then close it here so we have visibility and history of where it was added. 
Best, K.

**Comment by jhesketh** [comment]
Yep, you are required to have a verified email account to submit funding or volunteer applications.
