### ISSUE TITLE
Add per user salt

### ISSUE THREAD

**Issue by KathyReid** [zookeepr/zookeepr#350]
As a ZooKeepr administrator, I want to have each user's password salted rather than MD5 hashed so that passwords are stored in a more secure manner, therefore making ZooKeepr more robust. 

### Acceptance criteria
* Strong hash library is used
* Appropriate salt is used on a per user basis

**Comment by fmarier** [comment]
Done in #324 and #335.

Unfortunately, #336 replaced the strong password-derivation function (not available in Ubuntu 14.04) with a regular hash, which is weak but not embarrassingly weak like MD5.
