### ISSUE TITLE
Create a way for linux.conf.au seed data to be loaded

### ISSUE THREAD

**Issue by KathyReid** [zookeepr/zookeepr#363]
### User story
As an Administrator of ZooKeepr, I would like to be able to load a set of *seed data* so that I have the minimum amount of reference data in the database to be able to populate it for a linux.conf.au

### Acceptance criteria

The following seed data are required to be loaded
* @TODO
* The data is loaded via ... @TODO

@iseppi - would really appreciate your thoughts on the approach here

**Comment by lod** [comment]
@neillc fixed this in #406
