### ISSUE TITLE
lca2016 template: title element is still bootstrap default

### ISSUE THREAD

**Issue by KathyReid** [zookeepr/zookeepr#378]
### User story
As a Conference Organiser, I would like all ZooKeepr pages to have an accurate HTML Title element so that SEO rankings are as high as possible, leading to good publicity. 

### Acceptance criteria

* Title elements are page appropriate and match the H1 and URL of the page to yield SEO 'trifecta' - H1, URL and title match
* Title element is auto generated in .mako file

@noisymime: sorry Josh, I'm not sure how to fix this in the .mako file, if you can point me to an example I can probably issue a pull request. 

zookeepr/zkpylons/themes/lca2016/templates/base.mako

**Comment by dtbell91** [comment]
I resolved this in one of my many commits over the past week
