### ISSUE TITLE
Invoicing: easy way to do refunds

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#4]
Would invoicing benefit from a rewrite?

Something that could easily handle:
- refunds
- new invoices after the first one has been paid (e.g. adding dinner tickets)

Launchpad Details: [#LP356015](https://bugs.launchpad.net/bugs/356015) François Marier - 2009-04-06 14:41:06 +1000

**Comment by iseppi** [comment]
This has now largely been addressed by allowing negative quantities on invoice lines. This means a new invoice can be raised to negate an already paid invoice which will result in a negative total which can then be marked as paid when the conference has paid the delegate.

There is also a refund link on all paid invoices which will copy the entire invoice into the manual invoice form to allow editing the refund invoice before it is created allowing partial refunds.

Outstanding issues include:
 * editing a registration can void paid invoices. This should not be possible.
 * being registered should not require all invoices to be paid, just a paid ticket. This needs to account for multiple invoices where one could negate another.
 * editing a registration where there is a paid invoice should result in a delta invoice not an entire new invoice.

**Comment by iseppi** [comment]
There should be the ability to void a payment to allow for chargebacks by the payment gateway

**Comment by johnf** [comment]
Cleaning up some old issues I own
