### ISSUE TITLE
2016 theme GUI bug on login failure

### ISSUE THREAD

**Issue by lod** [zookeepr/zookeepr#412]
Seen on live linux.conf.au site, probably only an issue with 2016 theme.

Reproduce:
  Go to https://linux.conf.au/person/signin
  Enter details such that login fails

Problem:
  Bootstrap required notification is double height, wrapping in the your details incorrect message.
  Should be same height as form box so that borders look sweet.

Tested with Debian Iceweasel (aka Firefox) 39.0-1

![zk_login_gui_bug](https://cloud.githubusercontent.com/assets/243777/9240173/a84c7e2c-41a6-11e5-838d-9ec791766fac.png)

**Comment by dtbell91** [comment]
/me sighs
Yep, I've had to fix this in a bunch of other places as well...
Workaround: don't get your username/password wrong?

It's to do with what div you display the message in. I'll have a look.

**Comment by dtbell91** [comment]
This... isn't where I thought it would be.
Any guesses where the error messages get inserted from? There isn't anywhere in the .mako template which identifies where the error should be displayed. I'm guessing that the error is just inserted immediately before the textbox in all instances.

**Comment by noisymime** [comment]
Fixed in 834ff5cc44f31502e3047810b8175ce4949218f5
