### ISSUE TITLE
Zookeepr proposal code relies on person having a firstname

### ISSUE THREAD

**Issue by lod** [zookeepr/zookeepr#418]
We don't actually enforce that somebody has a first name
This causes code like person.firstname + person.lastname in controllers/proposal.py to break badly

**Comment by lod** [comment]
Also in other controllers: admin, invoice, miniconf_proposal, photocomp

**Comment by jhesketh** [comment]
I thought we forced people to fill out their extra information before submitting a proposal?

Either way, this does sound like a bug. Perhaps we need a method to fetch the name which checks if we have their full name and if not defaults to their email address or something else.
