### ISSUE TITLE
Registration-desk check in feature, with timestamp

### ISSUE THREAD

**Issue by duncan-zookeepr** [zookeepr/zookeepr#58]
It would be handy to be able to check in a delegate to know they have passed through the reg desk. This is of course backed up by a simple paper list, but if we can cross people off the list in an electronic way, then all the better.

It might be best to add the 'check-in' button to a Registration Desk role, and have the button for it available from the delegate profile page. That way, we could add a QR-code barcode to invoices/tickets that takes a delegate to their profile and a reg-desk user to the check-in.

It may be helpful to future conferences to know the pattern of reg-desk check-ins over time, so a time-stamp for the check-in would also be handy.

**Comment by lod** [comment]
The fulfilment system implemented in 2013 covers all of this.
