### ISSUE TITLE
remove lca from lca_info

### ISSUE THREAD

**Issue by CarlFK** [zookeepr/zookeepr#70]
For non lcas it would be nice if the info file wasn't called lca_info.   

How about just info?

Looks like it is used in about 80 places, most like this:
{{{
zookeepr/controllers/photocomp.py
24:from zookeepr.config import lca_info as lca_info
59:        date_day = lca_info.lca_info['date'] + datetime.timedelta(self.day)
}}}

**Comment by lod** [comment]
I fixed it in the referenced issue.
