### ISSUE TITLE
CFP: review paper order

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#8]
When reviewing papers, it is awesome that the system offers a random next paper for review. However, there are different types of submissions: papers, miniconfs and tutorials. Each one of them requires a different set of criteria to be applied as you review.

The system randomly picks a next submission for review when you've finished reviewing one. This may be of any type. That is extremely confusing and I have in fact mis-classed a tutorial submission for a normal paper submission in this way.

What it should do instead is to randomly pick a next submission of the *same type*. And when all submissions of he type are done, it should return to the full list of papers to be reviewed.

Launchpad Details: [#LP263968](https://bugs.launchpad.net/bugs/263968) Silvia Pfeiffer - 2008-09-02 21:40:03 +1000

**Comment by lod** [comment]
This should be closed as fixed.
I have confirmed that the requested behaviour is the current HEAD behaviour.
