### ISSUE TITLE
CFP: Allow talks to be assigned a cost, add budgetary estimates to the submission overviews

### ISSUE THREAD

**Issue by johnf** [zookeepr/zookeepr#9]
In the current process, submitters put in their (very unclear, bug 273777) requests for assistance. The programme committee then reviews the submissions and goes straight to the F2F meeting without prior evaluation of how many of the travel requests could possibly be funded.

This can give a misleading picture of how good the submissions are, since the submissions will consist of far more talks requesting funding than we can ever afford to accept.

In the weeks before final selection, cost estimates could be entered for various talks and in all the various ways of ordering the talks a running total of how much money has been spent by which talk could be displayed.

eg,

Rank 1,TALK NAME,COST: 3000.00   Total so far: 3000
Rank 2,TALK NAME2,COST: 50.00     Total so far: 3050
Rank 3,TALK NAME3, COST: 500.00  Total so far: 3550

This will enable much earlier determination of the point at which we will hit the budget limit.

Launchpad Details: [#LP273872](https://bugs.launchpad.net/bugs/273872) Mary Gardiner - 2008-09-24 17:44:06 +1000

**Comment by lod** [comment]
I have been considering some implementation options.

There are a number of flight price APIs, most charge a small amount per query.
QPX looks like the pick of the bunch. It is a Google API, I think they purchased it.
QPX offers 50 free queries a day, it still requires a signup and API key but is a lower hurdle.
Given two airfields the API provides a list of prices. I suggest we use the median of the cheapest ten prices, a decent estimate without being overly distorted by an outlier.

Finding the closest airfield to the conference is easy.
Finding the closest airfield to the submitter is a bit more exciting.
I think the best option is to convert the address to GPS coordinates. Find or build a table of airfield GPS coordinates and calculate the closest airfield.
Other options would be to use a lookup table of cities or countries to airfield. Or possibly use a mapping API to search for "airport". A close solution that gets 90% of submitters would be adequate, this opens the options up a bit.

Finally, doing a lookup like this is going to take time. Authentication, multiple APIs, and searching through decent sized tables makes this unsuitable for performing during a page load.

Caching the request is a must but running it asynchronously would also be much better. Either with a cron job that runs daily and updates the database or with a javascript request triggered by reviewers when required.

**Comment by johnf** [comment]
Cleaning up some old issues I own
