### ISSUE TITLE
json video_release

### ISSUE THREAD

**Issue by CarlFK** [zookeepr/zookeepr#93]
This should be part of the json export:

video_release = sa.Column(sa.types.Boolean)

https://github.com/zookeepr/zookeepr/blob/master/zookeepr/model/proposal.py#L201

**Comment by KathyReid** [comment]
@jhesketh Josh can you let me know if this requested change to the json export is now in master?
Thanks, K.

**Comment by lod** [comment]
Confirmed that it is in head.
